helloDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import path, include


# 声明views的处理函数
# view处理函数必须要求声明一个request参数，表示客户端的请求对象
# 请求对象中包含哪些信息：
#     - 请求头headers(method, content_type, path,path_info, get_full_path(), COOKIES)
#     - 字典结构请求信息
#        - request.COOKIES   Cookie信息
#        - request.GET  查询参数
#        - request.POST 表单参数
#  请求体： body(字节类型)
def index(request: HttpRequest):

    # return HttpResponse('<h1 style="color:green;">hi, Django</h1>')
    # 将数据渲染到模板中，并将渲染之后html响应给客户端
    return render(request, 'index.html',locals())

urlpatterns = [
    path('admin/', admin.site.urls),
    # 配置子路由，
    # include()导入app模块下urls.py中声明的所有子路由
    path('user/', include('mainapp.urls')),
    path('order/', include('orderapp.urls', namespace='order')),
    path('', index),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import user_list, user_list2, user_list3, add_user, all_store, count_fruit
from mainapp.views import update_user, delete_user, find_fruit, find_store
from mainapp import user_v


urlpatterns = [
    path('list', user_list3),
    path('add', add_user),
    path('update', update_user),
    path('del', delete_user),
    path('find', find_fruit),
    path('store', find_store),
    path('store_all', all_store),
    path('count', count_fruit),
    path('login', user_v.login)
]

orderapp/urls.py
#!/usr/bin/python3
# coding: utf-8
from django.urls import path, re_path
from django.conf.urls import url

from orderapp import views

app_name = 'orderapp'

urlpatterns = [
    path('list_999/<city_code>/<order_num>', views.order_list, name='list'),
    path('cancel/<uuid:order_num>', views.cancle_order, name='cancel'),
    re_path(r'^search/(?P<phone>1[3-57-9][\d]{9})$', views.search, name='search'),
    # url(r'^list2/(?P<city_code>\w+)/(?P<order_num>\d+)$', views.order_list)
    path('query', views.query)
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}
        爱心水果店
    {% endblock %}</title>

    {% include 'base_css.html' %}
    {% block css %}

    {% endblock %}
</head>
<body class="container">
{# 顶部的导航条 #}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><span id="logo" class="glyphicon glyphicon-heart-empty"></span>西安社区水果平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">精选水果 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">本周推荐</a></li>
            </ul>
            <form class="navbar-form navbar-left" style="margin-left: 100px">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="水果名或店名">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.login_user %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.session.login_user.name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改口令</a></li>
                            <li><a href="#">我的订单</a></li>
                            <li><a href="#">个人中心</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="#">注册</a></li>
                    <li><a href="#">登录</a></li>
                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="row">
    <div class="col-xs-8" style="height: 400px">
        {% block content %}

        {% endblock %}
    </div>
    <div class="col-xs-4">
        {% block right %}

        {% endblock %}
    </div>
</div>
<footer class="text-center">
    {% block footer %}
        @disen- 水果平台
    {% endblock %}
</footer>

{% include 'base_js.html' %}
</body>
</html>

templates/base_css.html
<link rel="stylesheet" href="/static/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/static/css/bootstrap.min.css">

templates/base_js.html
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>

templates/index.html
{% extends 'base.html' %}

{% block css %}
    <style>
        #logo{
            margin: 0 10px;
            display: inline-block;
            width: 15px;
            height: 15px;
        }
    </style>
{% endblock %}

{% block content %}

    <p>
        <a href="{% url 'orderapp:list' order_num=1002 city_code='xa' %}">订单</a>
    </p>

{% endblock %}

{% block footer %}
    {{ block.super }}
    <p>
        网备IDC： 10109192929
    </p>
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hi, 外层tempates 的List页</h1>
{% endblock %}